### ISSUE TITLE
UML class diagram

### ISSUE THREAD

**Issue by elias29** [TIS2019-FMFI/endurance-testing#13]

**Comment by Maros15873** [comment]
https://www.draw.io/#G1WjbGr2HG4htvNq0fF5aCi12ny4HREYAV

**Comment by Maros15873** [comment]
![Screenshot_2019-12-03 Untitled Diagram drawio - draw io](https://user-images.githubusercontent.com/47833876/70028762-cf4df000-15a5-11ea-9cbf-73e360dd5eb4.png)
