### ISSUE TITLE
UML state diagram

### ISSUE THREAD

**Issue by elias29** [TIS2019-FMFI/endurance-testing#14]
![State](https://user-images.githubusercontent.com/47821455/69078519-580e4d00-0a38-11ea-8fec-debf5a6561a8.png)

**Comment by elias29** [comment]
![State_2](https://user-images.githubusercontent.com/47821455/69761876-f309d400-1168-11ea-844a-5849a3c8e25d.png)

Nová verzia so zakomponovanými pripomienkami zo stretnutia (odstránenie stavu Pridaný produkt)

**Comment by pavelpetrovic** [comment]
za mna moze byt
