### ISSUE TITLE
Vytvorenie testovacích scenárov

### ISSUE THREAD

**Issue by elias29** [TIS2019-FMFI/endurance-testing#23]

**Comment by Maros15873** [comment]
[Testovacie scenare.docx](https://github.com/TIS2019-FMFI/endurance-testing/files/3972950/Testovacie.scenare.docx)

**Comment by Maros15873** [comment]
[Testovacie scenare.docx](https://github.com/TIS2019-FMFI/endurance-testing/files/4156611/Testovacie.scenare.docx)
