### ISSUE TITLE
Poznámky zo stretnutia so zadávateľom

### ISSUE THREAD

**Issue by elias29** [TIS2019-FMFI/endurance-testing#3]

**Comment by Maros15873** [comment]
[Podrobne poznamky zo stretnutia so zadavatelom.docx](https://github.com/TIS2019-FMFI/endurance-testing/files/3733421/Podrobne.poznamky.zo.stretnutia.so.zadavatelom.docx)

**Comment by Maros15873** [comment]
[Podrobne poznamky zo stretnutia so zadavatelom.docx](https://github.com/TIS2019-FMFI/endurance-testing/files/3739524/Podrobne.poznamky.zo.stretnutia.so.zadavatelom.docx)
Doplnene informacii.

**Comment by elias29** [comment]
Poznámky boli schválené zadávateľom.
