### ISSUE TITLE
Katalóg požiadaviek

### ISSUE THREAD

**Issue by elias29** [TIS2019-FMFI/endurance-testing#4]

**Comment by elias29** [comment]
[Katalóg požiadaviek.pdf](https://github.com/TIS2019-FMFI/endurance-testing/files/3748360/Katalog.poziadaviek.pdf)
Nahrávam prvú verziu katalógu požiadaviek

**Comment by pavelpetrovic** [comment]
- pre koho je dokument urceny
- prosim upresnit co sa mysli vetou "Aplikácia nebude automaticky vyhladávat a aktualizovat súbory."
- "slúžit na prepojenie" ???
- 2.1. je celkom nezrozumitelne
- 2.3. prosim vysvetlit, z je jedna alebo viacero pouzivat. roli

celu cast 3 treba pisat atomickymi poziadavkami, kazda ocislovana, kazda nesie len jednu informaciu, ktora tam moze byt alebo nemusi, nieco v takomto style:

K24-15: Aplikacia umoznuje vytvorit novy projekt.
K26-33: K vytvorenemu projektu aplikacia umoznuje zadat ZN a KD priamo.
K99-32: Aplikacia umoznuje vytvorit projekt automaticky zadanim nazvu XLSX suboru, ktory obsahuje ZN a KD, resp. jeho vybratim cez FileOpenDialog.

**Comment by elias29** [comment]
[Katalóg požiadaviek.pdf](https://github.com/TIS2019-FMFI/endurance-testing/files/3775237/Katalog.poziadaviek.pdf)
Nahrávam druhú verziu katalógu požiadaviek.

**Comment by pavelpetrovic** [comment]
dakujem za aktualizaciu KP. na prvy pohlad je to zatial hotove tak z 15%. zatial slaba robota...
pre inspiraciu si mozete pozriet, co zatial vytvorili Vasi kolegovia, ktori robia ten druhy projekt pre BOGE: https://github.com/TIS2019-FMFI/project-risk-analysis/files/3775284/katalog-poziadaviek.pdf

skuste sa k tomu aspon trochu priblizit...

k tomu, co uz je v dokumente pridavam moje komentare:
- KP nesluzi iba zadavatelom projektu, upravte to
- esencné casti a pridané hodnoty pouzivate vo vyzname pritiahnutom za vlasy, radsej jednoduchsie, napr. "nutna poziadavka" a "volitelna poziadavka, ktora bude implementovana iba, ak tim bude mat dostatocne zdroje"
- "vytvorenie databázy životností" navrhujem nejak upravit, napr. "vytvorenie systému na archiváciu údajov o výrobkoch a testoch životnosti"
- "cez nami vytvorený" nepouzivajte 1.osobu, v KP nikto nie je 1.osoba
- ", výstupom bude štruktúra." navrhujem zmenit napr. na ". Systém ich bude organizovať v stromovej štruktúre v súborovom systéme."
- "V neskoršej fáze projektu" - nerozumiem. Tento projekt ma iba jednu fazu. Bud to budete riesit Vy a potom nepiste nic o neskorsej faze, alebo jasne vysvetlite, ze to je mozne rozsirenie systemu do buducnosti, ktore je nad ramec tohto projektu.
- Interface nie je (len) pouzivatelske rozhranie. Ak chcete pouzit termin na pouzivatelske rozhranie, treba pouzit user interface
 - v 2.3. sa prosim vyjadrite, ci existuje iba jedna pouzivatelska rola, alebo viacero, ci pouzivatelia mozu pristupovat k systemu naraz a ci si system vyzaduje autentifikaciu, cize ci tam budu nejake ucty, alebo nie (ak nie, to vlastne znamena, ze ktokolvek software na firemnej sieti spusti, bude moct do neho chodit a nikto nevie, kto to bol)
- 2.5 - to si nemyslim :-), ale ak nic nemate, tak celu kapitolu mozete vypustit. mozete tam ale uviest, napr. ze system ma fungovat na os windows, ze pocitac bude prepojeny na lokalnej sieti so servrom
- 3.1 "vytvorit štruktúru v databáze" => "pre každý evidovaný výrobok vytvoriť..."
- 3.1  vo formalnom dokumente by kazdy obrazok mal mat popisku, napr. "Obr. 3.1. logická štruktúra organizácie dát v systéme."
- 3.1.4 "precítaním Zeichnungsnummer a Kunde z .xslx súboru" => ".. alebo ručným zadaním."
- 3.1.4 "ktorý má inú štruktúru." => prosim vysvetlit
- 3.1.5 velmi vela otvorenych otazok. ako suvisi datum testovania s polozkami struktury? je len jeden zoznam testovani pre kazdy vyrobok, alebo je tych zoznamov viac podla poloziek struktury? kolko takych datumov je mozne nastavit? da sa k nim pisat nejaka poznamka? ako sa daju zobrazit?  
- 3.2 tu nie je jasne, ci tym myslite obycajny file manager typu Windows Explorer, alebo ci tym myslite Vasu aplikaciu. v druhom pripade by bolo dobre najskor popisat, co vsetko v tej aplikacii je - ake stranky, menu, rezimy, zobrazenia a potom sa konkretne vyjadrit, co toto je za operacia. tiez nie je jasne odkial sa tam budu presuvat, napisali ste iba kam. presun ma vzdy dva konce: odkial a kam.
- 3.3 ked hovorite o "uvodnej strane", tak to naznacuje ako keby tam mohli byt aj ine, ale nic som sa o tom z dokumentu nedozvedel, vobec nie je jasne odkial sa tieto udaje vzali, ako sa do systemu zadavaju, ci sa daju neskor menit, ako sa daju zobrazit ostatne informacie, ktore system eviduje, atd atd atd...
- 3.6 Distribúcia: nerozumiem preco je tam slovo Distribucia, vyjadrite sa presne

takze ocakavam novu verziu, ktoru si este pred tym, ako to budete posielat zadavatelom precitam a dam spatnu vazbu. dakujem.

**Comment by elias29** [comment]
[Katalóg požiadaviek.pdf](https://github.com/TIS2019-FMFI/endurance-testing/files/3780359/Katalog.poziadaviek.pdf)
Nová verzia KP

**Comment by pavelpetrovic** [comment]
dakujem za aktualizaciu,
- nerozumiem vete "Aplikácia nebude automaticky vyhladávat
a aktualizovat súbory, teda vkladanie súborov je cisto manuálna práca
používatelov softvéru."
- struktura 2x
- odkial bude cerpat
- doriestit pojmy databaza/aplikacia/priecinky
- doriesit export
- ci naozaj netreba chranit pristup
- 3.3. nesedi
- a este vela dalsich uprav

**Comment by KosoScythe** [comment]
V linku prikladám novú verziu katalógu požiadaviek

https://docs.google.com/document/d/101rHZRipIg304ccGGPhkjrlVBFUrcwdM_NlXJvW8CRQ/edit#heading=h.avt7us4lhrtg

**Comment by pavelpetrovic** [comment]
je to už v stave, že si ho mám pozrieť, alebo to ešte kontrolujete?

**Comment by KosoScythe** [comment]
Dobrý deň,

KP je v stave, kedy si ho môžete pozrieť. V Sekcii GUI máme dve otázky na
zadávateľa, je to tam vyznačené, to doplníme hneď, ako príde odpoveď.

S pozdravom,
Tomáš Kosec

st 30. 10. 2019 o 10:41 Pavel Petrovič <notifications@github.com>
napísal(a):

**Comment by pavelpetrovic** [comment]
- vývojármi pridelenými
- (4.3). (priloha 4.3)
- v 4.3. chyba polozka Dokumentacia
