### ISSUE TITLE
Spísanie zoznamu požiadaviek

### ISSUE THREAD

**Issue by elias29** [TIS2019-FMFI/endurance-testing#6]

**Comment by KosoScythe** [comment]
Zoznam požiadaviek bol vytvorený
[Zoznam požiadaviek.docx](https://github.com/TIS2019-FMFI/endurance-testing/files/3733232/Zoznam.poziadaviek.docx)

**Comment by KosoScythe** [comment]
Zoznam požiadaviek bol schválený zadávateľom
