### ISSUE TITLE
Návrh používateľského rozhrania

### ISSUE THREAD

**Issue by elias29** [TIS2019-FMFI/endurance-testing#9]

**Comment by Maros15873** [comment]
![GUI 01](https://user-images.githubusercontent.com/47833876/68086512-319fbd80-fe4d-11e9-9ac3-716fcff77cb0.png)
![GUI 02](https://user-images.githubusercontent.com/47833876/68086514-319fbd80-fe4d-11e9-9732-bc30971f507b.png)
![GUI 03](https://user-images.githubusercontent.com/47833876/68086515-319fbd80-fe4d-11e9-8da1-9e0951ac39a1.png)

**Comment by Maros15873** [comment]
![T1](https://user-images.githubusercontent.com/47833876/69084353-5480c300-0a44-11ea-8bd3-1e68c6bdcdf1.png)
![T2](https://user-images.githubusercontent.com/47833876/69084355-55195980-0a44-11ea-9d44-ccfd8bf0cc3f.png)
